os: linux
dist: xenial
language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=30
  - ANDROID_BUILD_TOOLS_VERSION=30.0.0
  - ANDROID_ABI=armeabi-v7a

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;30"

script: true